openapi: 3.0.0
info:
  title: Swagger - App quản lý hội bồ câu Q8 TP HCM
  description: Swagger - App quản lý hội bồ câu Q8 TP HCM
  version: 1.0.0
components:
  schemas:
    UserResponseDto:
      $ref: 'components/common/UserResponseDto.yml#/components/schemas/UserResponseDto'
    UserLoginRequestDto:
      $ref: 'components/common/UserLoginRequestDto.yml#/components/schemas/UserLoginRequestDto'
    UserRegisterRequestDto:
      $ref: 'components/common/UserRegisterRequestDto.yml#/components/schemas/UserRegisterRequestDto'
tags:
  - name: Common
    description: Các api common
  - name: User
    description: Các api liên quan đến thông tin user
paths:
  /api/v1/login:
    post:
      tags:
        - Common
      summary: Đăng nhập
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequestDto'
            examples:
              sampleRequest:
                value:
                  username: "test1"
                  password: "test1"
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserResponseDto'
                example:
                  id: 1
                  username: "test1"
                  email: "test1@gmail.com"
                  phone: "0123456789"
                  address: "Quận 8, TP HCM"
                  birthday: "01-01-1999"
                  imgUrl: "/img/avatar/test1.jpg"
                  createdAt: "01-11-2024 10:00:00"
                  createdBy: 1
                  updatedAt: null
                  updatedBy: null
                  roleId: 1
        '401-04':
          description: Đăng nhập thất bại
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: 401-04
                  errorMessage:
                    type: string
                    example: Tài khoản không tồn tại.
        '401-05':
          description: Đăng nhập thất bại
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: 401-05
                  errorMessage:
                    type: string
                    example: Mật mã không đúng, vui lòng thử lại.
  /api/v1/logout:
    get:
      tags:
        - Common
      summary: Đăng xuất khỏi hệ thống
      description: Hủy bỏ phiên làm việc hiện tại của người dùng.
      responses:
        '200':
          description: Đăng xuất thành công
        '400':
          description: Bad request (user không tồn tại trong session)
  /api/v1/register:
    post:
      tags:
        - Common
      summary: Đăng ký thành viên mới
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterRequestDto'
            examples:
              sampleRequest:
                value:
                  username: "test"
                  password: "test123"
                  email: "test@gmail.com"
                  phone: "0123456789"
                  address: "Quận 8, TP HCM"
                  birthday: 01-01-1999
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserResponseDto'
                example:
                  id: 1
                  username: "test"
                  email: "test@gmail.com"
                  phone: "0123456789"
                  address: "Quận 8, TP HCM"
                  birthday: "01-01-1999"
                  imgUrl: null
                  createdAt: "01-11-2024 10:00:00"
                  createdBy: 1
                  updatedAt: null
                  updatedBy: null
                  roleId: 1
        '409-01':
          description: DuplicatedUserException
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: 409-01
                  errorMessage:
                    type: string
                    example: Username đã tồn tại.
        '409-02':
          description: DuplicatedUserException
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: 409-02
                  errorMessage:
                    type: string
                    example: Email đã được sử dụng.
        '409-03':
          description: DuplicatedUserException
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: 409-03
                  errorMessage:
                    type: string
                    example: SĐT đã được sử dụng.
        '400':
          description: Bad request (các lỗi khác như sai định dạng,...)
  /api/v1/user:
    post:
        tags:
          - User